name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: yolo_tak
          path: dist/*.whl
      - uses: actions/download-artifact@v4
        with:
          name: hash.txt
          path: hash.txt
      - name: Upload Release Asset to GitHub
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
